version: "3.7"

services:
  app:
    image: node:20-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql 
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
         
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: todos

volumes:
  mysql_data: